services:
  ivyEngine:
    image: axonivy/axonivy-engine:dev
    ports:
      - 8080:8080
    restart: unless-stopped
    volumes:
      - ../..:/workspaces:cached
    environment:
      JAVA_OPTS_IVY_SYSTEM: -Ddev.mode=true
  devcontainer:
    depends_on:
      - ivyEngine
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ../..:/workspaces:cached
    command: sleep infinity
    network_mode: service:ivyEngine
